version: "3"
services:
  postgresql:
    image: postgres:16           
    container_name: movie-tracker
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: "postgres"      
    ports:
      - "15432:5432"

